### ISSUE TITLE
Home Page Improvement

### ISSUE THREAD

**Issue by feelthecoder** [its-Kumar/dscweb#10]
![vks](https://user-images.githubusercontent.com/44005233/96038082-43267d80-0e84-11eb-95de-30e169645ae0.png)

In home page if we look at logo and name of club, they are too much close and also club name should be in single line. also there is lot of space. This problem can be seen in image as marked by red circle.

Other problem is that menu items name and icons are too much close. also see at login icon and login, they should be in linear.
this can seen in yellow circle.

Suggestion : Replace background with some cool tech image or a code image but that code should be written in small font. as current homepage background is making things messy.

**Comment by its-Kumar** [comment]
> Suggestion : Replace background with some cool tech image or a code image but that code should be written in small font. as current homepage background is making things messy.


@feelthecoder  these background image are actually a slider you can change the images by sliding to left or right.

**Comment by feelthecoder** [comment]
> > Suggestion : Replace background with some cool tech image or a code image but that code should be written in small font. as current homepage background is making things messy.
> 
> @feelthecoder these background image are actually a slider you can change the images by sliding to left or right.

@its-Kumar It will be good if this slider images moves automatically after a fix duration of time and change first image with another one with code written on it it small font.

**Comment by its-Kumar** [comment]
> In home page if we look at logo and name of club, they are too much close and also club name should be in single line. also there is lot of space. This problem can be seen in image as marked by red circle.

> Other problem is that menu items name and icons are too much close. 

I have fixed this in -
9d31f4a4368a30973654ac7d0e15165cd62e9880

**Comment by its-Kumar** [comment]
this have been fixed in 8d19956
