### ISSUE TITLE
Member Profile Details

### ISSUE THREAD

**Issue by lalitkapoor112000** [its-Kumar/dscweb#12]
Some Social Media links in the members profile are not opening need to check them again so that user is redirected to the correct profile page of the member.

**Comment by its-Kumar** [comment]
It is already mentioned in issue #6

**Comment by lalitkapoor112000** [comment]
okay sir

**Comment by its-Kumar** [comment]
@lalitkapoor112000 you can fix this and contribute, if you want

**Comment by its-Kumar** [comment]
Fixed in 8a282db367ffd2799f72f9b8596f5ec93dac994c
