### ISSUE TITLE
Home page issues

### ISSUE THREAD

**Issue by its-Kumar** [its-Kumar/dscweb#2]
Home page of the website has the following issues. Fix these issues as soon as possible.

1. About the club section
2. Members counts, project counts, etc.
3. Our work section
4. Add link of google form to "Join Us" button.
5. Add more pictures to the website specially indian pictures.

**Comment by its-Kumar** [comment]
> 5. Add more pictures to the website specially indian pictures.


I have fixed this

@shubham-recb fix other issues

**Comment by its-Kumar** [comment]
> 1. About the club section

I have fixed this 

b97ef437b94ece9927986be39cb4c4a2230105be

**Comment by shubham-recb** [comment]
Ok sir 👍

**Comment by its-Kumar** [comment]
> 4. Add link of google form to "Join Us" button.

I have fixed this in 671d687a1d1b558d0ffbedc3e4ae502c67376b42
