### ISSUE TITLE
Responsive [ navbar closing button ]

### ISSUE THREAD

**Issue by harikanani** [its-Kumar/dscweb#27]
# Mobile Version issue
- Navbar Closing button's color should be dark or opacity should be high to clearly visible.
- Navbar Closing button's Position should be at same at Hamburger Menu Button's Position.

### Here I'm attaching the look at mobile screen

![Screenshot_20210515-191415_Chrome](https://user-images.githubusercontent.com/54361799/118363397-d017ed80-b5b1-11eb-8565-69ceb26cd5b6.jpg)

**Comment by its-Kumar** [comment]
Thank you @harikanani 
can you tell me on which mobile device you are facing this issue

**Comment by its-Kumar** [comment]
@rajatyadav8540 @durgesh2001 please look into it.

**Comment by harikanani** [comment]
hey! @its-Kumar can i contribute to this bug?

**Comment by rajatyadav8540** [comment]
Ok I will do it

**Comment by its-Kumar** [comment]
> Ok I will do it

Ok I am assigning you this issue
