### ISSUE TITLE
Join Us Button

### ISSUE THREAD

**Issue by ankit595** [its-Kumar/dscweb#5]
Join Us button having no response... after clicking it.

**Comment by feelthecoder** [comment]
`<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfJN0mmEtTkeBWSnflFDcV55PmcfXB8ghfxtu4N8ga4V-Mgyg/viewform?embedded=true" width="640" height="3632" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>`

@its-Kumar This form is used to apply for member.

Suggestion : You may create a new page and embed this form there.

**Comment by its-Kumar** [comment]
I have changed this to - 

```diff
-<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfJN0mmEtTkeBWSnflFDcV55PmcfXB8ghfxtu4N8ga4V-Mgyg/viewform?embedded=true" width="640" height="3632" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

+<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfJN0mmEtTkeBWSnflFDcV55PmcfXB8ghfxtu4N8ga4V-Mgyg/viewform?embedded=true" width="100%" height="100%" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

```

**Comment by feelthecoder** [comment]
okay
