### ISSUE TITLE
team member's social id's link

### ISSUE THREAD

**Issue by VishnuVahanDas** [its-Kumar/dscweb#6]
Some member's social link are not working properly. I mentioned these members below.

Yagyik Shrivastava's facebook link not found
Yagyik Shrivastava's linkedin link not found

Anshu Rana's facebook link not found

Kritika Mishra's linkedin opens on clicking on facebook link
Kritika Mishra's git opens on clicking on linkedin link
Kritika Mishra's  facebook link not found.

Vikas kumar's  linkedin link not found
Vikas Kumar's  git link not found

Anubha Verma's linkedin link not found

Lalit Kapoor's git link not found

Mohd Aadil's facebook link not found
Mohd Aadil's git link not found

Priya Gupta's  git link not found

**Comment by luharinos** [comment]
@Vipul208 - Can you please guide me on the solution to this? I will like to contribute to it. Also, is this project considered under Hacktoberfest'20, if yes, kindly add it's label as well, please.

**Comment by its-Kumar** [comment]
@er-raoniz there are some `<a href="" >` links missing in the home page template named `home.html` you have to fix those links.
Any contribution to this project are welcome.
