### ISSUE TITLE
Competitions,Workshop,Training menu issue: Add Feature

### ISSUE THREAD

**Issue by feelthecoder** [its-Kumar/dscweb#9]
When we click on competition, a static page appear which contains some competitions information. Know more button is not working.

Suggestion :  It will be good if we can add/remove these competitions info from admin panel.

Also particular event may contains a one more button when know more page opens which ask user to register for that competitions using app. app link should be provided there.

In this every competition has to maintain it's status,whether it is completed or it is upcoming competition,

Similar suggestions for Workshop and Training Menu.

**Comment by its-Kumar** [comment]
Ok I'll do it
Thanks for the suggestion!

**Comment by feelthecoder** [comment]
thank you for consideration.
